# Generated by Django 2.2 on 2019-04-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
    ]
